# Site settings
name: Pou7

# Build settings
markdown: kramdown
highlighter: false
permalink: /:year/:month/:day/:title
exclude: [node_modules, bower_components, bower.json, Gruntfile.js, LICENSE, package.json]
